## Bài toán dự đoán giá nhà
- Đưa vào các thuộc tính căn nhà dự đoán giá (price)

### Bài tập
- Tiền xử lý dữ liệu cho trước: dữ liệu dự đoán giá nhà (xem thêm tại https://www.kaggle.com/harlfoxem/housesalesprediction)
- Xây dựng và đánh giá các mô hình KNN, Random Forest, Linear Regression, Ridge, Lasso
- Lựa chọn các siêu tham số cho từng mô hình
- So sánh các mô hình với nhau

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset = pd.read_csv('kc_house_data.csv')
dataset

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [ ]:
dataset.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [ ]:
df = pd.read_csv('kc_house_data.csv')

# Tiền xử lý cột date
df['date'] = pd.to_datetime(df['date'])
df['Years'] = df['date'].dt.year

X = df.drop(columns=['id', 'date', 'price', 'waterfront', 'view', 'condition'])  # Loại bỏ cột không cần chuẩn hóa
y = df['price']

# Chuẩn hóa các dữ liệu dạng numerical
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

df_scaled = pd.concat([X_scaled, df['Years'], df['view'], df['waterfront'], df['condition']], axis=1)


# Chia data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_scaled, y, test_size=0.2, random_state=42)

print(df_scaled)

       bedrooms  bathrooms  sqft_living  sqft_lot    floors     grade  \
0     -0.398737  -1.447464    -0.979835 -0.228321 -0.915427 -0.558836
1     -0.398737   0.175607     0.533634 -0.189885  0.936506 -0.558836
2     -1.473959  -1.447464    -1.426254 -0.123298 -0.915427 -1.409587
3      0.676485   1.149449    -0.130550 -0.244014 -0.915427 -0.558836
4     -0.398737  -0.149007    -0.435422 -0.169653 -0.915427  0.291916
...         ...        ...          ...       ...       ...       ...
21608 -0.398737   0.500221    -0.598746 -0.337424  2.788439  0.291916
21609  0.676485   0.500221     0.250539 -0.224386  0.936506  0.291916
21610 -1.473959  -1.772078    -1.154047 -0.332137  0.936506 -0.558836
21611 -0.398737   0.500221    -0.522528 -0.307076  0.936506  0.291916
21612 -1.473959  -1.772078    -1.154047 -0.338752  0.936506 -0.558836

       sqft_above  sqft_basement  yr_built  yr_renovated   zipcode       lat  \
0       -0.734708      -0.658681 -0.544898     -0.210128  1.870152 -0.352572
1        0.460841       0.245141 -0.681079      4.746678  0.879568  1.161568
2       -1.229834      -0.658681 -1.293892     -0.210128 -0.933388  1.283537
3       -0.891699       1.397515 -0.204446     -0.210128  1.085160 -0.283288
4       -0.130895      -0.658681  0.544548     -0.210128 -0.073636  0.409550
...           ...            ...       ...           ...       ...       ...
21608   -0.312039      -0.658681  1.293542     -0.210128  0.468382  1.004958
21609    0.629908      -0.658681  1.463768     -0.210128  1.272063 -0.356180
21610   -0.927928      -0.658681  1.293542     -0.210128  1.234683  0.247888
21611   -0.227505      -0.658681  1.123316     -0.210128 -0.952078 -0.184414
21612   -0.927928      -0.658681  1.259497     -0.210128  1.234683  0.245723

           long  sqft_living15  sqft_lot15     Years  Years  view  waterfront  \
0     -0.306079      -0.943355   -0.260715 -0.690655   2014     0           0
1     -0.746341      -0.432686   -0.187868 -0.690655   2014     0           0
2     -0.135655       1.070140   -0.172375  1.447901   2015     0           0
3     -1.271816      -0.914174   -0.284522 -0.690655   2014     0           0
4      1.199335      -0.272190   -0.192849  1.447901   2015     0           0
...         ...            ...         ...       ...    ...   ...         ...
21608 -0.938069      -0.666135   -0.412381 -0.690655   2014     0           0
21609 -1.051685      -0.228419   -0.203946  1.447901   2015     0           0
21610 -0.604321      -1.410253   -0.394141 -0.690655   2014     0           0
21611  1.028910      -0.841221   -0.420511  1.447901   2015     0           0
21612 -0.604321      -1.410253   -0.417948 -0.690655   2014     0           0

       condition
0              3
1              3
2              3
3              5
4              3
...          ...
21608          3
21609          3
21610          3
21611          3
21612          3

[21613 rows x 20 columns]

In [ ]:
pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.2.12-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from lazypredict) (8.1.7)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from lazypredict) (1.3.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from lazypredict) (2.1.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from lazypredict) (4.66.5)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from lazypredict) (1.4.2)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (from lazypredict) (4.4.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (from lazypredict) (2.1.1)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from lightgbm->lazypredict) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm->lazypredict) (1.13.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->lazypredict) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->lazypredict) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->lazypredict) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->lazypredict) (3.5.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost->lazypredict) (2.22.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->lazypredict) (1.16.0)
Downloading lazypredict-0.2.12-py2.py3-none-any.whl (12 kB)
Installing collected packages: lazypredict
Successfully installed lazypredict-0.2.12

100%|██████████| 29/29 [00:00<00:00, 1430.38it/s]

Empty DataFrame
Columns: [Accuracy, Balanced Accuracy, ROC AUC, F1 Score, Time Taken]
Index: []
Empty DataFrame
Columns: [Accuracy, Balanced Accuracy, ROC AUC, F1 Score, Time Taken]
Index: []

In [ ]:
# Build model
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Đầu tiên là LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

# Giờ ta thử với Ridge, Lasso

from sklearn.linear_model import Ridge, Lasso

# Ridge
param_grid = {'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}
grid_search_ridge = GridSearchCV(Ridge(), param_grid=param_grid, cv=5, scoring = 'r2')
grid_search_ridge.fit(X_train, y_train)

y_pred = grid_search_ridge.predict(X_test)

r2 = r2_score(y_test, y_pred)
print(f"R-squared (Ridge): {r2}")

# Lasso
param_grid = {'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}
grid_search_lasso = GridSearchCV(Lasso(), param_grid=param_grid, cv=5, scoring = 'r2')
grid_search_lasso.fit(X_train, y_train)

y_pred = grid_search_lasso.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f"R-squared (Lasso): {r2}")

# Giờ ta thử KNN

from sklearn.neighbors import KNeighborsRegressor
param_grid = {'n_neighbors': [3, 5, 7, 9, 11]}
grid_search_knn = GridSearchCV(KNeighborsRegressor(), param_grid=param_grid, cv=5, scoring = 'r2')
grid_search_knn.fit(X_train, y_train)

y_pred = grid_search_knn.predict(X_test)

r2 = r2_score(y_test, y_pred)
print(f"R-squared (KNN): {r2}")

# Cuối cùng là RandomForrest

from sklearn.ensemble import RandomForestRegressor
param_grid = [
   {'n_estimators' : [30, 50],
    'max_depth': [10, 30], 'random_state': [42]}
]
grid_search_rf = GridSearchCV(RandomForestRegressor(), param_grid = param_grid, cv = 3, scoring = "r2")
grid_search_rf.fit(X_train, y_train)


y_pred = grid_search_rf.predict(X_test)

r2 = r2_score(y_test, y_pred)
print(f"R-squared (Random Forest): {r2}")

R-squared: 0.702561034918392
R-squared (Ridge): 0.7025113138169174
R-squared (Lasso): 0.7023331887232394
R-squared (KNN): 0.7422474275785471
R-squared (Random Forest): 0.8466575982801898